include:
  - project: "infrastructure/gitlab-ci"
    ref: main
    file: "/templates/cloudbuild-common.gitlab-ci.yaml"
  - project: "infrastructure/gitlab-ci"
    ref: main
    file: "templates/deploy.gitlab-ci.yaml"

stages:
  - cloudbuild
  - deploy

cloudbuild:image:prod:
  only:
    - tokstock
  except:
    - tags
  extends: .cloudbuild:common

deploy:tokstock-prod:
  only:
    - tokstock
  except:
    - tags
  variables:
    APP_CONFIG: prod
    K8S_NAMESPACE: ${CI_PROJECT_ROOT_NAMESPACE}-prod
  extends: .deploy
  environment:
    name: bf
    on_stop: stop:tokstock-prod

stop:tokstock-prod:
  only:
    - tokstock
  except:
    - tags
  variables:
    APP_CONFIG: prod
    K8S_NAMESPACE: ${CI_PROJECT_ROOT_NAMESPACE}-prod
  extends: .stop
  environment:
    name: bf

cloudbuild:image:stage:
  only:
    - tokstock
  except:
    - tags
  extends: .cloudbuild:common

deploy:tokstock-stage:
  only:
    - tokstock
  except:
    - tags
  variables:
    APP_CONFIG: stage
    K8S_NAMESPACE: ${CI_PROJECT_ROOT_NAMESPACE}-stage
  extends: .deploy
  environment:
    name: bf
    on_stop: stop:tokstock-stage

stop:tokstock-stage:
  only:
    - tokstock
  except:
    - tags
  variables:
    APP_CONFIG: stage
    K8S_NAMESPACE: ${CI_PROJECT_ROOT_NAMESPACE}-stage
  extends: .stop
  environment:
    name: bf