include:
  - project: "infrastructure/gitlab-ci"
    ref: main
    file: "/templates/cloudbuild-common.gitlab-ci.yaml"
  - project: "infrastructure/gitlab-ci"
    ref: main
    file: "templates/deploy.gitlab-ci.yaml"

stages:
  - cloudbuild
  - deploy

cloudbuild:image:api:
  only:
    - dev
  except:
    - tags
  extends: .cloudbuild:common

deploy:api:
  only:
    - dev
  except:
    - tags
  extends: .deploy
  environment:
    name: stage
    on_stop: stop:api

stop:api:
  only:
    - dev
  except:
    - tags
  extends: .stop
  environment:
    name: stage

deploy:venom-stage:
  only:
    - dev
  extends: .deploy
  variables:
    APP_CONFIG: venom
  environment:
    name: stage
    on_stop: stop:venom-stage

stop:venom-stage:
  only:
    - dev
  extends: .stop
  variables:
    APP_CONFIG: venom
  environment:
    name: stage

cloudbuild:image:prod:
  only:
    - main
  except:
    - tags
  extends: .cloudbuild:common

deploy:prod:
  only:
    - main
  except:
    - tags
  extends: .deploy
  environment:
    name: prod
    on_stop: stop:prod

stop:prod:
  only:
    - main
  except:
    - tags
  extends: .stop
  environment:
    name: prod

cloudbuild:image:review:
  extends: .cloudbuild:common
  only:
    - merge_requests

deploy:review:
  extends: .deploy_review

stop:review:
  extends: .stop_review
