include:
  - project: "infrastructure/gitlab-ci"
    ref: main
    file: "/templates/cloudbuild-common.gitlab-ci.yaml"
  - project: "infrastructure/gitlab-ci"
    ref: main
    file: "templates/deploy.gitlab-ci.yaml"

stages:
  - cloudbuild
  - deploy

cloudbuild:image:stage:
  only:
    - stage
  except:
    - tags
  extends: .cloudbuild:common

deploy:stage-tokstock:
  only:
    - main
  except:
    - tags
  extends: .deploy
  environment:
    name: bf
    on_stop: stop:stage-tokstock
  variables:
    K8S_NAMESPACE: ${CI_PROJECT_ROOT_NAMESPACE}-stage
    APP_CONFIG: stage

stop:stage-tokstock:
  only:
    - main
  except:
    - tags
  extends: .stop
  environment:
    name: bf
  variables:
    K8S_NAMESPACE: ${CI_PROJECT_ROOT_NAMESPACE}-stage
    APP_CONFIG: stage

deploy:venom-stage:
  only:
    - main
  extends: .deploy
  environment:
    name: bf
    on_stop: stop:venom-stage
  variables:
    K8S_NAMESPACE: ${CI_PROJECT_ROOT_NAMESPACE}-stage
    APP_CONFIG: stage-venom

stop:venom-stage:
  only:
    - main
  extends: .stop
  environment:
    name: bf
  variables:
    K8S_NAMESPACE: ${CI_PROJECT_ROOT_NAMESPACE}-stage
    APP_CONFIG: stage-venom

deploy:v1-prod:
  only:
    - main
  extends: .deploy
  environment:
    name: bf
    on_stop: stop:v1-prod
  variables:
    K8S_NAMESPACE: ${CI_PROJECT_ROOT_NAMESPACE}-prod
    APP_CONFIG: prod-v1

stop:v1-prod:
  only:
    - main
  extends: .stop
  environment:
    name: bf
  variables:
    K8S_NAMESPACE: ${CI_PROJECT_ROOT_NAMESPACE}-prod
    APP_CONFIG: prod-v1

cloudbuild:image:prod:
  only:
    - main
  except:
    - tags
  extends: .cloudbuild:common

deploy:prod:
  only:
    - main
  except:
    - tags
  extends: .deploy
  environment:
    name: bf
    on_stop: stop:prod
  variables:
    K8S_NAMESPACE: ${CI_PROJECT_ROOT_NAMESPACE}-prod
    APP_CONFIG: prod

stop:prod:
  only:
    - main
  except:
    - tags
  extends: .stop
  environment:
    name: bf
  variables:
    K8S_NAMESPACE: ${CI_PROJECT_ROOT_NAMESPACE}-prod
    APP_CONFIG: prod

deploy:prod-venom:
  only:
    - main
  except:
    - tags
  extends: .deploy
  environment:
    name: bf
    on_stop: stop:prod-venom
  variables:
    K8S_NAMESPACE: ${CI_PROJECT_ROOT_NAMESPACE}-prod
    APP_CONFIG: prod-venom

stop:prod-venom:
  only:
    - main
  except:
    - tags
  extends: .stop
  environment:
    name: bf
  variables:
    K8S_NAMESPACE: ${CI_PROJECT_ROOT_NAMESPACE}-prod
    APP_CONFIG: prod-venom