include:
  - project: "infrastructure/gitlab-ci"
    ref: main
    file: "/templates/cloudbuild-common.gitlab-ci.yaml"
  - project: "infrastructure/gitlab-ci"
    ref: main
    file: "templates/deploy.gitlab-ci.yaml"

stages:
  - cloudbuild
  - deploy

cloudbuild:image:stage:
  only:
    - stage
  except:
    - tags
  extends: .cloudbuild:common

deploy:stage-tokstock:
  only:
    - stage
  except:
    - tags
  extends: .deploy
  environment:
    name: stage
    on_stop: stop:stage-tokstock

stop:stage-tokstock:
  only:
    - stage
  except:
    - tags
  extends: .stop
  environment:
    name: stage

deploy:vstage:
  only:
    - stage
  extends: .deploy
  variables:
    APP_CONFIG: vstage
  environment:
    name: stage
    on_stop: stop:vstage

stop:vstage:
  only:
    - stage
  extends: .stop
  variables:
    APP_CONFIG: vstage
  environment:
    name: stage

deploy:v1-prod:
  only:
    - main
  extends: .deploy
  variables:
    APP_CONFIG: v1
  environment:
    name: prod
    on_stop: stop:v1-prod

stop:v1-prod:
  only:
    - main
  extends: .stop
  variables:
    APP_CONFIG: v1
  environment:
    name: prod

cloudbuild:image:prod:
  only:
    - main
    - venom_main
  except:
    - tags
  extends: .cloudbuild:common

deploy:prod:
  only:
    - main
  except:
    - tags
  extends: .deploy
  environment:
    name: prod
    on_stop: stop:prod

stop:prod:
  only:
    - main
  except:
    - tags
  extends: .stop
  environment:
    name: prod

deploy:prod-venom:
  only:
    - main
    - venom_main
  except:
    - tags
  extends: .deploy
  environment:
    name: bf
    on_stop: stop:prod-venom
  variables:
    K8S_NAMESPACE: ${CI_PROJECT_ROOT_NAMESPACE}-prod
    APP_CONFIG: prod-venom

stop:prod-venom:
  only:
    - main
    - venom_main
  except:
    - tags
  extends: .stop
  environment:
    name: bf
  variables:
    K8S_NAMESPACE: ${CI_PROJECT_ROOT_NAMESPACE}-prod
    APP_CONFIG: prod-venom

