include:
  - project: "infrastructure/gitlab-ci"
    ref: main
    file: "/templates/cloudbuild-common.gitlab-ci.yaml"
  - project: "infrastructure/gitlab-ci"
    ref: main
    file: "templates/deploy.gitlab-ci.yaml"

stages:
  - cloudbuild
  - deploy

cloudbuild:image:api:
  only:
    - dev2
  except:
    - tags
  extends: .cloudbuild:common

deploy:api:
  only:
    - dev
  except:
    - tags
  extends: .deploy
  environment:
    name: stage
    on_stop: stop:api

stop:api:
  only:
    - dev
  except:
    - tags
  extends: .stop
  environment:
    name: stage

deploy:venomstg2:
  only:
    - dev2
  extends: .deploy
  variables:
    APP_CONFIG: venomstg2
  environment:
    name: stage
    on_stop: stop:venomstg2

stop:venomstg2:
  only:
    - dev2
  extends: .stop
  variables:
    APP_CONFIG: venomstg2
  environment:
    name: stage

deploy:venom-stage:
  only:
    - dev2
  extends: .deploy
  variables:
    APP_CONFIG: venom
  environment:
    name: stage
    on_stop: stop:venom-stage

stop:venom-stage:
  only:
    - dev2
  extends: .stop
  variables:
    APP_CONFIG: venom
  environment:
    name: stage

deploy:vstage:
  only:
    - dev2
  extends: .deploy
  variables:
    APP_CONFIG: vstage
  environment:
    name: stage
    on_stop: stop:vstage

stop:vstage:
  only:
    - dev2
  extends: .stop
  variables:
    APP_CONFIG: vstage
  environment:
    name: stage

deploy:v1-prod:
  only:
    - main
  extends: .deploy
  variables:
    APP_CONFIG: v1
  environment:
    name: prod
    on_stop: stop:v1-prod

stop:v1-prod:
  only:
    - main
  extends: .stop
  variables:
    APP_CONFIG: v1
  environment:
    name: prod

deploy:prod-reindex:
  only:
    - main
  extends: .deploy
  variables:
    APP_CONFIG: reindex
  environment:
    name: prod
    on_stop: stop:prod-reindex

stop:prod-reindex:
  only:
    - main
  extends: .stop
  variables:
    APP_CONFIG: reindex
  environment:
    name: prod

cloudbuild:image:prod:
  only:
    - main
  except:
    - tags
  extends: .cloudbuild:common

deploy:prod:
  only:
    - main
  except:
    - tags
  extends: .deploy
  environment:
    name: prod
    on_stop: stop:prod

stop:prod:
  only:
    - main
  except:
    - tags
  extends: .stop
  environment:
    name: prod

cloudbuild:image:review:
  extends: .cloudbuild:common
  only:
    - merge_requests

deploy:review:
  extends: .deploy_review

stop:review:
  extends: .stop_review
