include:
  - project: "infrastructure/gitlab-ci"
    ref: main
    file: "/templates/cloudbuild-common.gitlab-ci.yaml"
  - project: "infrastructure/gitlab-ci"
    ref: main
    file: "templates/deploy.gitlab-ci.yaml"

stages:
  - cloudbuild
  - deploy

cloudbuild:image:api:
  only:
    - dev
  except:
    - tags
  extends: .cloudbuild:common

deploy:api:
  only:
    - dev
  except:
    - tags
  extends: .deploy
  environment:
    name: stage
    on_stop: stop:api

stop:api:
  only:
    - dev
  except:
    - tags
  extends: .stop
  environment:
    name: stage

deploy:venom-stage:
  only:
    - dev
  extends: .deploy
  variables:
    APP_CONFIG: venom
  environment:
    name: stage
    on_stop: stop:venom-stage

stop:venom-stage:
  only:
    - dev
  extends: .stop
  variables:
    APP_CONFIG: venom
  environment:
    name: stage

deploy:tokstock-prod-v1:
  only:
    - tokstock-prod
  extends: .deploy
  variables:
    APP_CONFIG: prod-v1
    K8S_NAMESPACE: ${CI_PROJECT_ROOT_NAMESPACE}-prod
  environment:
    name: bf
    on_stop: stop:tokstock-prod-v1

stop:tokstock-prod-v1:
  only:
    - tokstock-prod
  extends: .stop
  variables:
    APP_CONFIG: prod-v1
    K8S_NAMESPACE: ${CI_PROJECT_ROOT_NAMESPACE}-prod
  environment:
    name: bf

deploy:prod-reindex:
  only:
    - main
  extends: .deploy
  variables:
    APP_CONFIG: reindex
  environment:
    name: prod
    on_stop: stop:prod-reindex

stop:prod-reindex:
  only:
    - main
  extends: .stop
  variables:
    APP_CONFIG: reindex
  environment:
    name: prod

cloudbuild:image:tokstock-prod:
  only:
    - tokstock-prod
  except:
    - tags
  extends: .cloudbuild:common

deploy:tokstock-prod:
  only:
    - tokstock-prod
  except:
    - tags
  variables:
    APP_CONFIG: prod
    K8S_NAMESPACE: ${CI_PROJECT_ROOT_NAMESPACE}-prod
  extends: .deploy
  environment:
    name: bf
    on_stop: stop:tokstock-prod

stop:tokstock-prod:
  only:
    - tokstock-prod
  except:
    - tags
  variables:
    APP_CONFIG: prod
    K8S_NAMESPACE: ${CI_PROJECT_ROOT_NAMESPACE}-prod
  extends: .stop
  environment:
    name: bf

cloudbuild:image:review:
  extends: .cloudbuild:common
  only:
    - merge_requests

deploy:review:
  extends: .deploy_review

stop:review:
  extends: .stop_review
